### ISSUE TITLE
Add a translated Portuguese version of "What is the PSF"

### ISSUE THREAD

**Issue by deboraazevedo** [valerybriz/python_infographics#1]
Hello!

I suggested to @valerybriz to also have a Portuguese version of the "What is the PSF" infographic! Here I have the text in pt-br:

#O que é a PSF?
A Python Software Foundation (PSF) é uma organização sem fins lucrativos que tem os direitos autorais da linguagem de programação Python.

Sua missão é dar suporte e facilitar o crescimento de uma comunidade de programadores internacional diversa.

E também promover o avanço da linguagem Python.

#E como fazem isso?

Organizando a PyCon.
Protegendo e distribuindo o código da linguagem Python, suas bibliotecas, documentação e outros recursos relacionados para o público de forma gratuita.
Arrecadando fundos para dar suporte a serviços e e programar para a comunidade. ambém proveêm apoio através de patrocínios diretamente a conferências e eventos por todo o mundo.

**Comment by valerybriz** [comment]
thank you so much for your help, we are already working to get this portuguese version with your translations :)

**Comment by valerybriz** [comment]
I'm closing this issue since the portuguese version is ready! thank you so much!
