### ISSUE TITLE
Some Typos in the Pt-Br text

### ISSUE THREAD

**Issue by felipe-xavier** [valerybriz/python_infographics#2]
The text for **Raising Funds** yellow block located at the bottom-right position.

Current Text:
"Arrecadando fundos para dar suporte a serviços e **e programar** para a comunidade. **Ambém proveêm** apoio através de patrocínios diretamente a conferências e eventos por todo o mundo".

Suggested Text:
"Arrecadando fundos para dar suporte a **programas e serviços** para a comunidade. **Também proveem** apoio através de patrocínios diretamente a conferências e eventos por todo o mundo".

**Comment by deboraazevedo** [comment]
Thnak you @felipe-xavier for your contribution! @valerybriz how do we proceed? create a new image file?

**Comment by valerybriz** [comment]
Thank you @felipe-xavier  for the feedback, yes indeed @deboraazevedo we are already working on the new image to replace the first one :) I'll let you know when it is ready 

Thank you!

**Comment by valerybriz** [comment]
I'm closing this issue since the infographics are now ready with the typo fixes thank you very much!!

**Comment by felipe-xavier** [comment]
Thank you, guys, for the work! Well done!
